/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    NutButton: typeof import('@nutui/nutui-taro')['Button']
    NutCol: typeof import('@nutui/nutui-taro')['Col']
    NutEllipsis: typeof import('@nutui/nutui-taro')['Ellipsis']
    NutMenu: typeof import('@nutui/nutui-taro')['Menu']
    NutMenuItem: typeof import('@nutui/nutui-taro')['MenuItem']
    NutRow: typeof import('@nutui/nutui-taro')['Row']
    NutSearchbar: typeof import('@nutui/nutui-taro')['Searchbar']
    NutSpace: typeof import('@nutui/nutui-taro')['Space']
    NutTag: typeof import('@nutui/nutui-taro')['Tag']
  }
}
